apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.images.ac_authserver.name }}-cm"
  labels:
    buildDate: {{ now | date "2006-01-02T15.04.05" }}
    app: {{ .Values.app.name }}
data:
  env.ac: |
    AC_LOGS_DIR={{ .Values.ac_authserver.environment.AC_LOGS_DIR | quote }}
    AC_TEMP_DIR={{ .Values.ac_authserver.environment.AC_TEMP_DIR | quote }}
    AC_LOGIN_DATABASE_INFO={{ .Values.ac_authserver.environment.AC_LOGIN_DATABASE_INFO | quote }}

    DOCKER_AC_ENV_FILE="conf/dist/env.ac"
    ACORE_COMPONENT="authserver"