apiVersion: v1
kind: ConfigMap
metadata:
  name: ac-authserver-conf
data:
  authserver.conf: |
    ###############################################
    # AzerothCore Auth Server configuration file #
    ###############################################
    [authserver]

    ###################################################################################################
    # EXAMPLE CONFIG
    #
    #    LogsDir
    LogsDir = ""

    MaxPingTime = 30
    RealmServerPort = 3724
    BindIP = "0.0.0.0"
    EnableProxyProtocol = 0
    PidFile = ""
    UseProcessors = 0
    ProcessPriority = 0
    RealmsStateUpdateDelay = 20
    WrongPass.MaxCount = 0
    WrongPass.BanTime = 600
    WrongPass.BanType = 0
    WrongPass.Logging = 0
    BanExpiryCheckInterval = 60
    StrictVersionCheck = 0
    SourceDirectory = ""
    MySQLExecutable = ""
    TempDir = ""
    IPLocationFile = ""
    AllowLoggingIPAddressesInDatabase = 1

    LoginDatabaseInfo = "ac-database-service.azerothcore-wotlk.svc.cluster.local;3306;acore;acore;acore_auth"

    Database.Reconnect.Seconds = 15
    Database.Reconnect.Attempts = 20
    LoginDatabase.WorkerThreads = 1
    LoginDatabase.SynchThreads = 1

    EnableTOTP = 0
    TOTPMasterSecret =
    Updates.EnableDatabases = 1
    Updates.AutoSetup = 1
    Updates.Redundancy = 1
    Updates.ArchivedRedundancy = 0
    Updates.AllowRehash = 1
    Updates.CleanDeadRefMaxCount = 3

    Appender.Console=1,5,0,"1 9 3 6 5 8"
    Appender.Auth=2,5,0,Auth.log,w
    Logger.root=4,Console Auth

