apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.images.ac_worldserver.name }}
  labels:
    buildDate: {{ now | date "2006-01-02T15.04.05" }}
    containerName: {{ .Values.images.ac_worldserver.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.images.ac_worldserver.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.images.ac_worldserver.name }}
    spec:
      containers:
        - name: {{ .Values.images.ac_worldserver.name }}
          image: {{ .Values.images.ac_worldserver.image }}:{{ .Values.images.ac_worldserver.tag }}
          # command: ["/azerothcore/entrypoint.sh", "worldserver"]
          command: ["/azerothcore/env/dist/bin/worldserver"]
          stdin: true
          tty: true
          imagePullPolicy: {{ .Values.images.ac_worldserver.pullPolicy }}
          ports:
            - containerPort: 8085
              name: world-external
            - containerPort: 7878
              name: soap-external
          envFrom:
            - configMapRef:
                name: "{{ .Values.images.ac_worldserver.name }}-cm"
          volumeMounts:
            - name: env
              mountPath: /conf/dist/env.ac
              subPath: env.ac
            - name: ac-client-data-volume
              mountPath: /azerothcore/env/dist/data
            - name: worldserver-conf
              mountPath: /azerothcore/env/dist/etc/worldserver.conf
              subPath: worldserver.conf
      volumes:
        - name: ac-client-data-volume
          persistentVolumeClaim:
            claimName: ac-client-data-pvc
        - name: env
          configMap:
            name: "{{ .Values.images.ac_worldserver.name }}-cm"
        - name: worldserver-conf
          configMap:
            name: "{{ .Values.images.ac_worldserver.name }}-conf"
            items:
              - key: worldserver.conf
                path: worldserver.conf
      securityContext:
        fsGroup: 0
        runAsUser: 1000
        runAsGroup: 1000
