apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.images.ac_database.name }}-pvc"
  labels:
    app: {{ .Values.app.name }}
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ac_database.pvc.storage }}