apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.images.ac_db_import.name }}-pvc"
  namespace: {{ .Values.app.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi