apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ac-client-data-pvc
  namespace: {{ .Values.app.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi