apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ac-client-data-pvc
  labels:
    app: azerothcore-wotlk
    component: client-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi