apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.images.ac_authserver.name }}-service"
  namespace: {{ .Values.app.name }}
  labels:
    buildDate: {{ now | date "2006-01-02T15.04.05" }}
    name: {{ .Values.images.ac_authserver.name }}
spec:
  ports:
    - port: 3724
      targetPort: 3724
  selector:
    app: {{ .Values.images.ac_authserver.name }}
