# Default values for repo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  name: azerothcore-wotlk

images:
  ac_database:
    name: ac-database
    image: mysql:8.3
    pullPolicy: IfNotPresent
    port: 3306
  ac_db_import:
    name: ac-db-import
    image: acore/ac-wotlk-db-import:master
    pullPolicy: IfNotPresent
  ac_worldserver:
    name: ac-worldserver
    image: acore/ac-wotlk-worldserver:master
    pullPolicy: IfNotPresent
  ac_authserver:
    name: ac-authserver
    image: acore/ac-wotlk-authserver:master
    pullPolicy: IfNotPresent
  ac_client_data_init:
    name: ac-client-data-init
    image: acore/ac-wotlk-client-data:master
    pullPolicy: IfNotPresent
  ac_tools:
    name: ac-tools
    image: acore/ac-wotlk-tools:master
    pullPolicy: IfNotPresent


podAnnotations: {}
podLabels: {}

ac_database:
  healthcheck:
    test: "/usr/bin/mysql --user=root --password=$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
    interval: 5
    timeout: 10
    retries:
      liveness: 40
      readiness: 1

ac_db_import:
  environment:
    AC_DATA_DIR: "/azerothcore/env/dist/data"
    AC_LOGS_DIR: "/azerothcore/env/dist/logs"
    AC_LOGIN_DATABASE_INFO: "ac-database-service;3306;root;${MYSQL_ROOT_PASSWORD};acore_auth"
    AC_WORLD_DATABASE_INFO: "ac-database-service;3306;root;${MYSQL_ROOT_PASSWORD};acore_world"
    AC_CHARACTER_DATABASE_INFO: "ac-database-service;3306;root;${MYSQL_ROOT_PASSWORD};acore_characters"

ac_worldserver:
  environment:
    AC_DATA_DIR: "/azerothcore/env/dist/data"
    AC_LOGS_DIR: "/azerothcore/env/dist/logs"
    AC_LOGIN_DATABASE_INFO: "ac-database-service;3306;acore;acore;acore_auth"
    AC_WORLD_DATABASE_INFO: "ac-database-service;3306;acore;acore;acore_world"
    AC_CHARACTER_DATABASE_INFO: "ac-database-service;3306;acore;acore;acore_characters"
  ports:
    - 8085:8085
    - 7878:7878

ac_authserver:
  environment:
    AC_LOGS_DIR: "/azerothcore/env/dist/logs"
    AC_TEMP_DIR: "/azerothcore/env/dist/temp"
    AC_LOGIN_DATABASE_INFO: "ac-database-service;3306;acore;acore;acore_auth"

ac_client_data_init:
  environment:
    {}

service:
  type: ClusterIP
  port: 80

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http